// Bilingual content
const CONTENT = {
  fr: {
    nav: ['Hôtel', 'Chambres', 'Tarifs', 'Restaurant', 'Séminaires', 'Groupes', 'Fécamp / Étretat', 'Infos pratiques'],
    reserve: 'Réserver',
    tagline: 'Yport · Côte d\u2019Albâtre',
    heroSub: 'Entre Fécamp & Étretat',
    heroTitle: ['Une maison', 'normande', 'à 100 m de la mer.'],
    heroLede: 'Treize chambres au pied des falaises, une terrasse baignée de soleil, une table qui sent bon la Manche. L\u2019Hôtel Normand vous accueille au cœur du petit port d\u2019Yport depuis trois générations.',
    heroCta: 'Découvrir l\u2019hôtel',
    heroCall: 'Appeler la réception',
    sinceLabel: 'Maison de famille depuis',
    sinceYear: '1897',
    introEyebrow: '— La maison',
    introTitle: 'Un petit hôtel de charme,\nau pied des falaises.',
    introBody: [
      'De l\u2019Hôtel Normand, quelques pas vous amèneront sur la plage d\u2019Yport, au pied des falaises de la côte d\u2019Albâtre. Situé au cœur de la station balnéaire, petite sœur d\u2019Étretat, l\u2019Hôtel Normand est un petit établissement atypique de treize chambres, au charme envoûtant.',
      'Vous serez séduit par cette maison typiquement normande, surmontée de son drôle de clocher perché, et par l\u2019accueil chaleureux d\u2019une famille qui vit ici, et qui aime recevoir.',
    ],
    factsTitle: 'À retenir',
    facts: [
      ['13', 'chambres à taille humaine'],
      ['100 m', 'de la plage d\u2019Yport'],
      ['11 km', 'd\u2019Étretat — 7 km de Fécamp'],
      ['1897', 'année de la maison'],
    ],
    amenities: [
      ['Wi-Fi gratuit', 'dans tout l\u2019hôtel'],
      ['Petit déjeuner', 'continental servi en salle ou terrasse'],
      ['Restaurant', 'de bistrot, ouvert midi & soir'],
      ['Terrasse', 'paysagée, abritée du vent'],
      ['Massages', 'bien-être sur réservation'],
      ['Animaux', 'acceptés sur demande'],
    ],
    roomsEyebrow: '— Les chambres',
    roomsTitle: 'Treize chambres, treize ambiances.',
    roomsLede: 'Toutes nos chambres sont rénovées dans un esprit simple et lumineux. Certaines offrent une vue sur la vallée, d\u2019autres sur la terrasse fleurie.',
    roomsCta: 'Voir toutes les chambres',
    rooms: [
      { name: 'La Classique', price: '89', desc: 'Lit double, salle d\u2019eau privée, vue rue pavée.', tag: 'de 1 à 2 personnes' },
      { name: 'La Supérieure', price: '109', desc: 'Lit queen, fenêtre sur jardin, baignoire.', tag: 'de 1 à 2 personnes' },
      { name: 'La Familiale', price: '139', desc: 'Chambre communicante, idéale pour 4.', tag: 'jusqu\u2019à 4 personnes' },
    ],
    priceFrom: 'à partir de',
    priceNight: '/ nuit',
    restoEyebrow: '— Le restaurant',
    restoTitle: 'Bistronomique,\nles saveurs iodées\nde la Manche.',
    restoBody: 'Imaginez une terrasse baignée de lumière et abritée du vent, des assiettes aux saveurs iodées dressées avec générosité, une ambiance de bistrot familiale toute en délicatesse. Sur l\u2019ardoise, produits frais et locaux se disputent la vedette — des moules-frites aux plats plus raffinés selon les arrivages et l\u2019inspiration du Chef.',
    restoCta: 'Réserver une table',
    restoFacts: ['Du mercredi au dimanche', 'Déjeuner 12 h – 13 h', 'Dîner 19 h – 20 h', 'Terrasse abritée'],
    restoMenusTitle: 'Nos formules',
    restoMenus: [
      { name: 'Menu déjeuner', price: '22 €', desc: 'Formule du jour, entrée + plat + dessert. Servi du mercredi au dimanche midi.' },
      { name: 'Carte bistronomique', price: 'à la carte', desc: 'L\u2019ardoise du Chef au gré des arrivages : poissons de la Manche, viandes locales, légumes de saison.' },
      { name: 'Menu groupes & autocaristes', price: '35 – 40 €', desc: 'Menu dédié pour associations et groupes en autocar. Parking autocar à 100 m.' },
      { name: 'Demi-pension & étape affaires', price: 'sur demande', desc: 'Dîner, nuitée, petit déjeuner. Idéal pour déplacements professionnels à Fécamp ou Étretat.' },
    ],
    restoRoomsTitle: 'Deux salles,\ndeux ambiances.',
    restoRooms: [
      { name: 'La grande salle', desc: 'Lumineuse et conviviale, elle accueille jusqu\u2019à 40 couverts pour le déjeuner comme pour le dîner.' },
      { name: 'La petite salle', desc: 'Privatisable, idéale pour les repas de famille, déjeuners entre amis ou réunions intimistes.' },
      { name: 'La terrasse', desc: 'Paysagée et abritée du vent, baignée de soleil dès les beaux jours. L\u2019été y déploie son ambiance iodée.' },
    ],
    restoQuote: 'Une cuisine de bistrot qui fait la part belle\naux producteurs locaux.',
    restoQuoteSrc: 'Guide Petit Futé',
    locationEyebrow: '— Le pays de Caux',
    locationTitle: 'Yport,\nentre Fécamp & Étretat.',
    locationBody: 'Yport est l\u2019un des derniers villages de pêcheurs authentiques de la Côte d\u2019Albâtre. On y flâne sur le perré, on y mange des bulots au café du port, on y grimpe sur la falaise d\u2019Amont pour le coucher du soleil. Étretat et ses célèbres arches sont à onze kilomètres ; Fécamp et son Palais Bénédictine à sept.',
    locationPlaces: [
      ['01', 'Plage d\u2019Yport', '2 min à pied'],
      ['02', 'Falaise d\u2019Amont', '15 min à pied'],
      ['03', 'Étretat', '15 min en voiture'],
      ['04', 'Fécamp', '10 min en voiture'],
      ['05', 'Le Havre', '40 min en voiture'],
      ['06', 'Gare de Bréauté-Beuzeville', '20 min'],
    ],
    reviewsEyebrow: '— On en parle',
    reviewsTitle: 'Ce que disent nos voyageurs.',
    reviews: [
      { stars: 5, text: 'Un petit bijou au bord de la mer. L\u2019accueil est d\u2019une gentillesse rare, la chambre impeccable, et le dîner mémorable.', who: 'Clémentine R.', src: 'Booking · avril 2026' },
      { stars: 5, text: 'On y revient chaque année depuis cinq ans. C\u2019est la Normandie comme on la rêve : simple, sincère, savoureuse.', who: 'Henri & Colette L.', src: 'Google · mars 2026' },
      { stars: 5, text: 'Le charme de l\u2019ancien avec tout le confort moderne. La terrasse au petit-déjeuner est un rêve.', who: 'Sophie M.', src: 'Tripadvisor · février 2026' },
    ],
    galleryEyebrow: '— Album',
    galleryTitle: 'Promenade en images.',
    ctaEyebrow: '— Nous écrire',
    ctaTitle: 'Envie de venir\nnous voir ?',
    ctaBody: 'Nous répondons tous les jours de 8 h à 21 h. Pour une réservation de dernière minute, un appel est toujours plus sûr.',
    ctaPhone: '+33 (0)2 35 27 30 76',
    ctaEmail: 'contact@hotel-normand.fr',
    ctaAddress: '2 rue Alfred Nunès · 76111 Yport',
    footerCol1: 'L\u2019Hôtel Normand',
    footerCol1Body: 'Petit hôtel de charme à Yport, pays de Caux. Treize chambres, une table, une terrasse, une famille.',
    footerNav: 'Naviguer',
    footerContact: 'Nous trouver',
    footerHours: 'Réception 8 h – 21 h\nRestaurant 12 h – 14 h · 19 h – 21 h',
    footerLegal: '© 2026 L\u2019Hôtel Normand · Tous droits réservés · Mentions légales',
    bookEyebrow: 'Réservation',
    bookArrival: 'Arrivée',
    bookDeparture: 'Départ',
    bookGuests: 'Voyageurs',
    bookAdults: 'Adultes',
    bookChildren: 'Enfants',
    bookCheck: 'Vérifier les disponibilités',
    bookOr: 'ou par téléphone au',
  },
  en: {
    nav: ['Hotel', 'Rooms', 'Rates', 'Restaurant', 'Seminars', 'Groups', 'Fécamp / Étretat', 'Useful info'],
    reserve: 'Book',
    tagline: 'Yport · Alabaster Coast',
    heroSub: 'Between Fécamp & Étretat',
    heroTitle: ['A Norman', 'family house', '100 metres from the sea.'],
    heroLede: 'Thirteen rooms at the foot of the cliffs, a sun-drenched terrace, a table that tastes of the Channel. L\u2019Hôtel Normand has welcomed travellers to the little port of Yport for three generations.',
    heroCta: 'Discover the hotel',
    heroCall: 'Call reception',
    sinceLabel: 'Family-run since',
    sinceYear: '1897',
    introEyebrow: '— The house',
    introTitle: 'A small hotel of character,\nat the foot of the cliffs.',
    introBody: [
      'From L\u2019Hôtel Normand, a few steps will take you to Yport beach, at the foot of the Alabaster Coast cliffs. In the heart of the seaside village — little sister to Étretat — the Hôtel Normand is a singular thirteen-room inn, full of quiet charm.',
      'You will be won over by this typically Norman house with its curious perched bell tower, and by the warm welcome of a family who lives here, and loves to host.',
    ],
    factsTitle: 'At a glance',
    facts: [
      ['13', 'human-scale rooms'],
      ['100 m', 'from Yport beach'],
      ['11 km', 'to Étretat · 7 km to Fécamp'],
      ['1897', 'the house\u2019s year'],
    ],
    amenities: [
      ['Free Wi-Fi', 'throughout the hotel'],
      ['Breakfast', 'served indoors or on the terrace'],
      ['Restaurant', 'bistro dining, lunch & dinner'],
      ['Terrace', 'sheltered, landscaped'],
      ['Massage', 'wellness treatments on request'],
      ['Pets', 'welcome on request'],
    ],
    roomsEyebrow: '— The rooms',
    roomsTitle: 'Thirteen rooms, thirteen moods.',
    roomsLede: 'All our rooms are refreshed in a simple, light-filled style. Some overlook the valley, others the flowered terrace.',
    roomsCta: 'See all rooms',
    rooms: [
      { name: 'The Classic', price: '89', desc: 'Double bed, private bathroom, cobbled-street view.', tag: '1 to 2 guests' },
      { name: 'The Superior', price: '109', desc: 'Queen bed, garden window, bathtub.', tag: '1 to 2 guests' },
      { name: 'The Family', price: '139', desc: 'Connecting room, perfect for four.', tag: 'up to 4 guests' },
    ],
    priceFrom: 'from',
    priceNight: '/ night',
    restoEyebrow: '— The restaurant',
    restoTitle: 'Bistronomic,\nthe sea salt flavours\nof the Channel.',
    restoBody: 'Picture a light-filled terrace sheltered from the wind, plates of sea-salt flavours plated generously, the delicate atmosphere of a family bistro. On the chalkboard, fresh local produce takes centre stage — from moules-frites to more refined dishes, depending on the catch and the Chef\u2019s inspiration.',
    restoCta: 'Book a table',
    restoFacts: ['Wednesday to Sunday', 'Lunch 12 – 1 pm', 'Dinner 7 – 8 pm', 'Sheltered terrace'],
    restoMenusTitle: 'Our menus',
    restoMenus: [
      { name: 'Lunch menu', price: '€22', desc: 'Daily set menu: starter + main + dessert. Served Wednesday to Sunday at lunch.' },
      { name: 'À la carte', price: 'à la carte', desc: 'The Chef\u2019s chalkboard, by the catch of the day: Channel fish, local meats, seasonal vegetables.' },
      { name: 'Groups & coaches', price: '€35 – €40', desc: 'Dedicated menu for associations and coach groups. Coach parking 100 m away.' },
      { name: 'Half-board & business stopover', price: 'on request', desc: 'Dinner, overnight stay, breakfast. Ideal for business travel to Fécamp or Étretat.' },
    ],
    restoRoomsTitle: 'Two dining rooms,\ntwo moods.',
    restoRooms: [
      { name: 'The main room', desc: 'Bright and convivial, seats up to 40 for lunch as well as dinner.' },
      { name: 'The small room', desc: 'Private-hire option, perfect for family meals, lunches with friends or intimate meetings.' },
      { name: 'The terrace', desc: 'Landscaped and sheltered, sun-drenched in fair weather. Summer unfolds its sea-salt atmosphere here.' },
    ],
    restoQuote: 'Bistro cooking that puts\nlocal producers centre stage.',
    restoQuoteSrc: 'Guide Petit Futé',
    locationEyebrow: '— Pays de Caux',
    locationTitle: 'Yport,\nbetween Fécamp & Étretat.',
    locationBody: 'Yport is one of the last authentic fishing villages of the Alabaster Coast. Stroll the seafront, eat whelks at the harbour café, climb the Amont cliff for sunset. Étretat and its famous arches are eleven kilometres away; Fécamp and its Bénédictine Palace, seven.',
    locationPlaces: [
      ['01', 'Yport beach', '2 min walk'],
      ['02', 'Amont cliff', '15 min walk'],
      ['03', 'Étretat', '15 min drive'],
      ['04', 'Fécamp', '10 min drive'],
      ['05', 'Le Havre', '40 min drive'],
      ['06', 'Bréauté-Beuzeville station', '20 min'],
    ],
    reviewsEyebrow: '— Word of mouth',
    reviewsTitle: 'What our guests say.',
    reviews: [
      { stars: 5, text: 'A little gem by the sea. The welcome is rare and warm, the room impeccable, dinner unforgettable.', who: 'Clémentine R.', src: 'Booking · April 2026' },
      { stars: 5, text: 'We\u2019ve come back every year for five years. This is Normandy as one dreams it — simple, sincere, flavourful.', who: 'Henri & Colette L.', src: 'Google · March 2026' },
      { stars: 5, text: 'Old-world charm with modern comfort. Breakfast on the terrace is a dream.', who: 'Sophie M.', src: 'Tripadvisor · February 2026' },
    ],
    galleryEyebrow: '— Album',
    galleryTitle: 'A walk in pictures.',
    ctaEyebrow: '— Write to us',
    ctaTitle: 'Care to pay\nus a visit?',
    ctaBody: 'We answer every day between 8 am and 9 pm. For a last-minute booking, a phone call is always safer.',
    ctaPhone: '+33 (0)2 35 27 30 76',
    ctaEmail: 'contact@hotel-normand.fr',
    ctaAddress: '2 rue Alfred Nunès · 76111 Yport',
    footerCol1: 'L\u2019Hôtel Normand',
    footerCol1Body: 'A small hotel of character in Yport, Pays de Caux. Thirteen rooms, one table, a terrace, a family.',
    footerNav: 'Explore',
    footerContact: 'Find us',
    footerHours: 'Reception 8 am – 9 pm\nRestaurant 12 – 2 pm · 7 – 9 pm',
    footerLegal: '© 2026 L\u2019Hôtel Normand · All rights reserved · Legal notice',
    bookEyebrow: 'Booking',
    bookArrival: 'Arrival',
    bookDeparture: 'Departure',
    bookGuests: 'Guests',
    bookAdults: 'Adults',
    bookChildren: 'Children',
    bookCheck: 'Check availability',
    bookOr: 'or call us at',
  },
};

window.CONTENT = CONTENT;
